src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_comment = null;

    #[ORM\Column(length: 255)]
    private ?string $content_comment = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $commentator = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recipe $recipe = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateComment(): ?\DateTimeInterface
    {
        return $this->date_comment;
    }

    public function setDateComment(\DateTimeInterface $date_comment): static
    {
        $this->date_comment = $date_comment;

        return $this;
    }

    public function getContentComment(): ?string
    {
        return $this->content_comment;
    }

    public function setContentComment(string $content_comment): static
    {
        $this->content_comment = $content_comment;

        return $this;
    }

    public function getCommentator(): ?User
    {
        return $this->commentator;
    }

    public function setCommentator(?User $commentator): static
    {
        $this->commentator = $commentator;

        return $this;
    }

    public function getRecipe(): ?Recipe
    {
        return $this->recipe;
    }

    public function setRecipe(?Recipe $recipe): static
    {
        $this->recipe = $recipe;

        return $this;
    }
}

src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IngredientRepository::class)]
class Ingredient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_ingredient = null;

    #[ORM\ManyToMany(targetEntity: Recipe::class, mappedBy: 'ingredient')]
    private Collection $recipes;

    public function __construct()
    {
        $this->recipes = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->name_ingredient ;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameIngredient(): ?string
    {
        return $this->name_ingredient;
    }

    public function setNameIngredient(string $name_ingredient): static
    {
        $this->name_ingredient = $name_ingredient;

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): static
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes->add($recipe);
            $recipe->addIngredient($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): static
    {
        if ($this->recipes->removeElement($recipe)) {
            $recipe->removeIngredient($this);
        }

        return $this;
    }
}

src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title_recipe = null;

    #[ORM\Column(type: 'text')]
    private ?string $description_recipe = null;

    #[ORM\Column]
    private ?int $prep_time = null;

    #[ORM\Column]
    private ?int $cook_time = null;

    #[ORM\Column]
    private ?int $number_serving = null;

    #[ORM\Column(length: 255)]
    private ?string $picture_recipe = null;

    #[ORM\ManyToOne(inversedBy: 'recipe')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $creator_recipe = null;

    #[ORM\ManyToMany(targetEntity: Ingredient::class, inversedBy: 'recipes')]
    private Collection $ingredient;

    #[ORM\ManyToOne(inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(type: 'text')]
    private ?string $procedure = null;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Like::class, orphanRemoval: true)]
    private Collection $likes;




    public function __construct()
    {
        $this->ingredient = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->title_recipe;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleRecipe(): ?string
    {
        return $this->title_recipe;
    }

    public function setTitleRecipe(string $title_recipe): static
    {
        $this->title_recipe = $title_recipe;

        return $this;
    }

    public function getDescriptionRecipe(): ?string
    {
        return $this->description_recipe;
    }

    public function setDescriptionRecipe(string $description_recipe): static
    {
        $this->description_recipe = $description_recipe;

        return $this;
    }

    public function getPrepTime(): ?int
    {
        return $this->prep_time;
    }

    public function setPrepTime(int $prep_time): static
    {
        $this->prep_time = $prep_time;

        return $this;
    }

    public function getCookTime(): ?int
    {
        return $this->cook_time;
    }

    public function setCookTime(int $cook_time): static
    {
        $this->cook_time = $cook_time;

        return $this;
    }

    public function getNumberServing(): ?int
    {
        return $this->number_serving;
    }

    public function setNumberServing(int $number_serving): static
    {
        $this->number_serving = $number_serving;

        return $this;
    }

    public function getPictureRecipe(): ?string
    {
        return $this->picture_recipe;
    }

    public function setPictureRecipe(string $picture_recipe): static
    {
        $this->picture_recipe = $picture_recipe;

        return $this;
    }

    public function getCreatorRecipe(): ?User
    {
        return $this->creator_recipe;
    }

    public function setCreatorRecipe(?User $creator_recipe): static
    {
        $this->creator_recipe = $creator_recipe;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredient(): Collection
    {
        return $this->ingredient;
    }

    public function addIngredient(Ingredient $ingredient): static
    {
        if (!$this->ingredient->contains($ingredient)) {
            $this->ingredient->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): static
    {
        $this->ingredient->removeElement($ingredient);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getProcedure(): ?string
    {
        return $this->procedure;
    }

    public function setProcedure(string $procedure): static
    {
        $this->procedure = $procedure;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRecipe($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRecipe() === $this) {
                $comment->setRecipe(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setRecipe($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getRecipe() === $this) {
                $like->setRecipe(null);
            }
        }

        return $this;
    }




}

templates/single_recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Single-recipe
{% endblock %}


{% block content %}


	<!-- SubHeader -->
	<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="{{ asset('assets/images/header.png') }}" data-natural-width="1400" data-natural-height="300">
		<div id="sub_header">
			<div class="container" id="sub_content">
				<div class="row">
					<div class="col-md-12">
						<h1>Single Recipe</h1>
						<!-- End bread-crums -->
					</div>
				</div>
				<!-- End row -->
			</div>
			<!-- End container -->
		</div>
	</section>
	<!-- End SubHeader -->
	<div class="white_bg">
		<div class="container margin_60">
			<div class="row">
				<div class="col-md-8">
					<div class="post-inner">
						<div class="info-icons">
							<div class="semipart">
								<i class="ic icon-x-forks"></i>
								Prep Time
								{{ recipe.prepTime }}
								minutes
							</div>
							<div class="semipart">
								<i class="ic icon-timer"></i>
								Cook Time
								{{ recipe.cookTime }}
								minutes
							</div>
							<div class="semipart">
								<i class="ic icon-community2"></i>
								Serving For
								{{ recipe.numberServing }}
								People
							</div>
						</div>

						<div class="post-img">
							<img src="{{ asset('assets/images/' ~ recipe.pictureRecipe) }}" alt="{{ recipe.titleRecipe }}">
						</div>

						<h3 class="post-title">{{ recipe.titleRecipe }}</h3>
						<div class="post-meta">
							<span class="meta-author">
								<i class="far fa-user"></i>
								<a href="#">{{ recipe.creatorRecipe.firstname }}
									{{ recipe.creatorRecipe.lastname }}</a>
							</span>
						</div>

						<div class="post-content">
							<h4>Description</h4>
							<p>{{ recipe.descriptionRecipe }}</p>

							<h4>Procedure</h4>
							<p>{{ recipe.procedure }}</p>

							<h4>Ingredient</h4>
							<div class="ul_list">
								<ul>
									{% for ingredient in recipe.ingredient %}
										<li>{{ ingredient.nameIngredient }}</li>
									{% endfor %}
								</ul>
							</div>
							<!-- End Ingredient -->
						</div>
					</div>
					<div
						class="stars-tags"><!-- this div to make line -->
					</div>
					<!-- start comment -->
					<div id="commentlist" class="page-content">
						<h3>Comments
						</h3>
						<ol class="commentlist clearfix">
							{% for comment in recipe.comments %}
								<li class="comment">
									<div class="comment-body clearfix">
										<div class="avatar">
											<img
											alt="" src="http://placehold.it/100x100">
										<!-- Remplacez par l'image du commentateur si disponible -->
										</div>
										<div class="comment-text">
											<div class="author clearfix">
												<div class="comment-meta">
													<span>{{ comment.commentator.firstname }}
														{{ comment.commentator.lastname }}</span>
													<div class="date">{{ comment.dateComment|date('F j, Y \\a\\t H:i') }}</div>
												</div>
											</div>
											<div class="text">
												<p>{{ comment.contentComment }}</p>
											</div>
										</div>
									</div>
								</li>
							{% else %}
								<li>No comments yet.</li>
							{% endfor %}
						</ol>
						<!-- End commentlist -->
					</div>
					<!-- end comment -->

					<!-- start form comment -->
					<div class="comment-form">
						<h3>Leave a reply</h3>
						<form action="{{ path('recipe_add_comment', {'id': recipe.id}) }}" method="post">
							<div class="form-group">
								<textarea id="comment" name="comment" rows="8" class="form-control" required></textarea>
							</div>
							<button type="submit" class="btn btn-primary">Post Comment</button>
						</form>
					</div>
					<!-- end form comment -->


				</div>
				<aside class="col-md-4 sidebar sticky-sidebar">
					<div class="theiaStickySidebar">
						<div class="widget widget-list">
							<div class="widget-title">
								<i class="far fa-folder-open"></i>
								Category
							</div>
							<ul>
								<li class="cat-item">
									<a href="#">{{ recipe.category.NameCategory }}</a>
								</li>
							</ul>
						</div>
						<!-- End widget -->
					</div>
				</aside>
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</div>
	<!-- End white_bg -->


{% endblock %}