src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $content_post = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Topic $topic = null;

    #[ORM\ManyToOne(inversedBy: 'post')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $poster = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContentPost(): ?string
    {
        return $this->content_post;
    }

    public function setContentPost(string $content_post): static
    {
        $this->content_post = $content_post;

        return $this;
    }

    public function getTopic(): ?Topic
    {
        return $this->topic;
    }

    public function setTopic(?Topic $topic): static
    {
        $this->topic = $topic;

        return $this;
    }

    public function getPoster(): ?User
    {
        return $this->poster;
    }

    public function setPoster(?User $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

}

src/Entity/Topic.php
<?php

namespace App\Entity;

use App\Repository\TopicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TopicRepository::class)]
class Topic
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title_topic = null;

    #[ORM\Column(length: 255)]
    private ?string $description_topic = null;

    #[ORM\OneToMany(mappedBy: 'topic', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $posts;



    public function __toString()
    {
        return $this->title_topic;
    }
    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleTopic(): ?string
    {
        return $this->title_topic;
    }

    public function setTitleTopic(string $title_topic): static
    {
        $this->title_topic = $title_topic;

        return $this;
    }

    public function getDescriptionTopic(): ?string
    {
        return $this->description_topic;
    }

    public function setDescriptionTopic(string $description_topic): static
    {
        $this->description_topic = $description_topic;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setTopic($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getTopic() === $this) {
                $post->setTopic(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'creator_recipe', targetEntity: Recipe::class, orphanRemoval: true)]
    private Collection $recipe;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture_user = null;

    #[ORM\OneToMany(mappedBy: 'commentator', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'liker', targetEntity: Like::class, orphanRemoval: true)]
    private Collection $likes;

    #[ORM\OneToMany(mappedBy: 'poster', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $post;


    public function __construct()
    {
        $this->recipe = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->post = new ArrayCollection();


    }
    public function __toString()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipe(): Collection
    {
        return $this->recipe;
    }

    public function addRecipe(Recipe $recipe): static
    {
        if (!$this->recipe->contains($recipe)) {
            $this->recipe->add($recipe);
            $recipe->setCreatorRecipe($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): static
    {
        if ($this->recipe->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getCreatorRecipe() === $this) {
                $recipe->setCreatorRecipe(null);
            }
        }

        return $this;
    }


    public function getPictureUser(): ?string
    {
        return $this->picture_user;
    }

    public function setPictureUser(?string $picture_user): static
    {
        $this->picture_user = $picture_user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setCommentator($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCommentator() === $this) {
                $comment->setCommentator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setLiker($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getLiker() === $this) {
                $like->setLiker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPost(): Collection
    {
        return $this->post;
    }

    public function addPost(Post $post): static
    {
        if (!$this->post->contains($post)) {
            $this->post->add($post);
            $post->setPoster($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->post->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getPoster() === $this) {
                $post->setPoster(null);
            }
        }

        return $this;
    }



}

src/Controller/CommunityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Topic;
use App\Repository\TopicRepository;
use App\Repository\PostRepository;



class CommunityController extends AbstractController
{
    #[Route('/community', name: 'app_community')]
    public function index(TopicRepository $topicRepository): Response
    {
        $topics = $topicRepository->findAll(); // Récupère tous les topics

        return $this->render('community/index.html.twig', [
            'topics' => $topics,
        ]);
    }

    #[Route('/community/{id}', name: 'app_topic')]
    public function showTopic($id, TopicRepository $topicRepository, PostRepository $postRepository): Response
    {
        $topic = $topicRepository->find($id); // Récupère le topic par son ID
        $posts = $postRepository->findBy(['topic' => $topic]); // Récupère les posts associés à ce topic

        return $this->render('community/post.html.twig', [
            'topic' => $topic,
            'posts' => $posts,
        ]);
    }

}

templates/community/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Historic
{% endblock %}

{% block content %}

	<!-- SubHeader -->
<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="{{ asset('assets/images/header.png') }}" data-natural-width="1400" data-natural-height="300">
		<div id="sub_header">
			<div class="container" id="sub_content">
				<div class="row">
					<div class="col-md-12">
						<h1>Community</h1>
						<div class="bread-crums">
							<a href="#">Home</a>
							<span class="bread-crums-span">&raquo;</span>
							<span class="current">Community</span>
						</div>
						<!-- End bread-crums -->
					</div>
				</div>
				<!-- End row -->
			</div>
			<!-- End container -->
		</div>
	</section>
	<!-- End SubHeader -->
	<div class="white_bg">
		<div class="container margin_60">
			<div class="row">
				{% for topic in topics %}
					<div class="col-lg-6 col-md-6 col-xs-12">
						<div class="col-community">
							<div class="thumb">
								<i class="ic icon-community"></i>
							</div>
							<div class="inner">
								<h3>
									<a href="{{ path('app_topic', {'id': topic.id}) }}">{{ topic.titleTopic }}</a>
								</h3>

								<p>{{ topic.DescriptionTopic }}</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</div>
	<!-- End white_bg -->
{% endblock %}

templates/community/post.html.twig
{% extends 'base.html.twig' %}


{% block title %}Historic
{% endblock %}

{% block content %}
	<!-- SubHeader -->
	<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="{{ asset('assets/images/header.png') }}" data-natural-width="1400" data-natural-height="300">
		<div id="sub_header">
			<div class="container" id="sub_content">
				<div class="row">
					<div class="col-md-12">
						<h1>Single Topic Community</h1>
						<div class="bread-crums">
							<a href="#">Home</a>
							<span class="bread-crums-span">&raquo;</span>
							<a href="#">Community</a>
							<span class="bread-crums-span">&raquo;</span>
							<span class="current">Single Topic Community</span>
						</div>
						<!-- End bread-crums -->
					</div>
				</div>
				<!-- End row -->
			</div>
			<!-- End container -->
		</div>
	</section>
	<!-- End SubHeader -->


	<div class="white_bg">
		<div class="container margin_60">
			<div class="row">
				<div class="col-md-12">
					<h3>
						title of the Topic :
						{{ topic.titleTopic }}</h3>
					<ul class="topics">
						{% for post in posts %}
							<li>
								<div class="row">
									<div class="col-md-2">
										<div class="topic-author">
											<a href="#" class="author-avatar">
												{% if post.poster.pictureUser %}
													<img src="{{ asset('assets/images/users/' ~ post.poster.pictureUser) }}" alt="User Image" style="width: 100px; height: 100px; object-fit: cover;">
												{% else %}
													<img src="{{ asset('assets/images/users/inconnu.png') }}" alt="Default User Image" style="width: 100px; height: 100px; object-fit: cover;">
												{% endif %}
											</a>
											<a href="#" title="" class="author-name">
												{{ post.poster.firstname }}
												{{ post.poster.lastname }}
											</a>
										</div>
										<!-- End topic-author -->
									</div>
									<div class="col-md-10">
										<div class="topic-content">
											<p>{{ post.contentPost|raw }}</p>
										</div>
										<!-- End topic-content -->
									</div>
								</div>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>

		<!-- End container -->
	</div>
	<!-- End white_bg -->
{% endblock %}